# Ej 7 - Repaso de probabilidad

In [1]:
import numpy as np

# nro mails
nmails = 6
# words
nwords = 4

# conteo de words + clasificacion Spam = 1 / Ham = 0 
wcount = np.zeros((nmails, nwords+1))
wcount[0,:] = [3,3,1,6,1]
wcount[1,:] = [1,4,7,1,0]
wcount[2,:] = [1,4,3,1,0]
wcount[3,:] = [4,2,1,5,1]
wcount[4,:] = [1,3,4,2,0]
wcount[5,:] = [2,4,5,1,0]

print(wcount)

[[3. 3. 1. 6. 1.]
 [1. 4. 7. 1. 0.]
 [1. 4. 3. 1. 0.]
 [4. 2. 1. 5. 1.]
 [1. 3. 4. 2. 0.]
 [2. 4. 5. 1. 0.]]


In [32]:
# Calculo de probabilidades
# Indices mails SPAM/HAM
idx_spam = np.nonzero(wcount[:,-1])
idx_ham = np.argwhere(wcount[:,-1]==0)                      
# Probabilidad SPAM/HAM
p_spam = np.size(idx_spam)/nmails
p_ham = np.size(idx_ham)/nmails

# Probabilidad de ocurrencia c/word: P(wi/S)
sum_w_spam = np.sum(wcount[idx_spam,0:nwords],axis=1)
nwords_spam = np.sum(wcount[idx_spam,0:nwords]) 
p_w_spam = sum_w_spam/nwords_spam
# Probabilidad de ocurrencia c/word: P(wi/H)
sum_w_ham = np.sum(wcount[idx_ham,0:nwords],axis=0)
nwords_ham = np.sum(wcount[idx_ham,0:nwords]) 
p_w_ham = sum_w_ham/nwords_ham

print(p_w_spam)
print(p_w_ham)

[[0.28 0.2  0.08 0.44]]
[[0.11363636 0.34090909 0.43181818 0.11363636]]


In [43]:
# Test nuevo mail 
tcount = np.array([4,1,1,5])

# Probabilidad SPAM
p_t_spam = p_spam*np.prod(np.power(p_w_spam,tcount))

# Probabilidad HAM
p_t_ham = p_ham*np.prod(np.power(p_w_ham,tcount))

if p_t_spam < p_t_ham:
    print('El mail es HAM')
else: 
    print('El mail es SPAM')

El mail es SPAM
